package com.pandcaspian.indicator;

public class CommonDefine {
	//_________________________  Generated by ESP_Master_Common_Convertor begin

	// Common Define
	//-----------------------------------------------------------------------------
	//
	final static byte ESP_ProtocolRevision_ =          (byte)2      ; //
	
	// ID MessageIcons
	final static byte ID_QuestionIcon_ =               (byte)1      ; //
	final static byte ID_MemoryIcon_ =                 (byte)2      ; //
	final static byte ID_ErrorIcon_ =                  (byte)3      ; //
	final static byte ID_WiFiIcon_ =                   (byte)4      ; //
	final static byte ID_CautionIcon_ =                (byte)5      ; //
	final static byte ID_DeleteIcon_ =                 (byte)6      ; //
	final static byte ID_InformationIcon_ =            (byte)7      ; //
	final static byte ID_WaitIcon_ =                   (byte)8      ; //
	
	// NetStatus Status Codes
	final static byte NetStatus_UnDefined_ =           (byte)0      ; // Undefined Status
	final static byte NetStatus_OK_ =                  (byte)1      ; // OK (Connected)
	final static byte NetStatus_Disconnected_ =        (byte)2      ; // Disconnected
	final static byte NetStatus_Connecting_ =          (byte)3      ; // Connecting...
	final static byte NetStatus_NotFound_ =            (byte)4      ; // SSID Not Found (Unavailable)
	final static byte NetStatus_WrongPassword_ =       (byte)5      ; // Wrong Password
	final static byte NetStatus_ConnectFail_ =         (byte)6      ; // Connection Failed
	final static byte NetStatus_Idle_ =                (byte)7      ; // Station is Idle
	
	// Internet Status Codes
	final static byte InternetStatus_UnDefined_ =      (byte)0      ; // Undefined Status
	final static byte InternetStatus_Available_ =      (byte)1      ; // OK (Internet is Available)
	final static byte InternetStatus_Error_ =          (byte)2      ; // Error, Internet Unavailable
	
	
	//  Hex    Esc.   Name (1967)
	// = 0x0    \0     Null                             NUL
	// = 0x1           Start of Heading                 SOH
	// = 0x2           Start of Text                    STX
	// = 0x3           End of Text                      ETX
	// = 0x4           End of Transmission              EOT
	// = 0x5           Enquiry                          ENQ
	// = 0x6           Acknowledgement                  ACK
	// = 0x7    \a     Bell                             BEL
	// = 0x8    \b     Backspace[e][f]                  BS
	// = 0x9    \t     Horizontal Tab[g]                HT
	// = 0x0A   \n     Line Feed                        LF
	// = 0x0B   \v     Vertical Tab                     VT
	// = 0x0C   \f     Form Feed                        FF
	// = 0x0D   \r     Carriage Return[h]               CR
	// = 0x0E          Shift Out                        SO
	// = 0x0F          Shift In                         SI
	// = 0x10          Data Link Escape                 DLE
	// = 0x11          Device Control 1                 DC1
	// = 0x12          Device Control 2                 DC2
	// = 0x13          Device Control 3                 DC3
	// = 0x14          Device Control 4                 DC4
	// = 0x15          Negative Acknowledgement         NAK
	// = 0x16          Synchronous Idle                 SYN
	// = 0x17          End of Transmission Block        ETB
	// = 0x18          Cancel                           CAN
	// = 0x19          End of Medium                    EM
	// = 0x1A          Substitute                       SUB
	// = 0x1B   \e[i]  Escape[j]                        ESC
	// = 0x1C          File Separator                   FS
	// = 0x1D          Group Separator                  GS
	// = 0x1E          Record Separator                 RS
	// = 0x1F          Unit Separator                   US
	// = 0x7F          Delete[l][f]                     DEL
	
	// Protocol
	//-----------------------------------------------------------------------------
	// List of ComOut(Commands Out) Master send to ESP 7
	
	final static byte FCSTS_ =          (byte)15         ; // Fix Curent String Transfer Size
	final static int FBPS_ =           512        ; // Fix Bulk Packet Size
	
	final static byte Graphic_ReportFormat_ =         (byte)0      ; //
	final static byte HTML_File_ReportFormat_ =        (byte)1      ; //
	
	
	final static byte SOH            = (byte)0x01       ; // Start of Heading
	final static byte EOT            = (byte)0x04       ; // End of Transmission
	final static byte SYN            = (byte)0x16       ; // Synchronous Idle (synchronize or cancel curent transmit or operation)
	final static byte ENQ            = (byte)0x05       ; // Enquiry( continue file sending )                         
	
	
	// Prefix
	final static byte ESP_Prefix_GetNum               = (byte)'<'       ; // 
	final static byte ESP_Prefix_SetNum               = (byte)'>'       ; // 
	final static byte ESP_Prefix_GetStr               = (byte)'{'       ; // 
	final static byte ESP_Prefix_SetStr               = (byte)'}'       ; // 
	final static byte ESP_Prefix_Request              = (byte)'['       ; // 
	final static byte ESP_Prefix_Order                = (byte)']'       ; // 
	final static byte ESP_Prefix_GetBulk              = (byte)'('       ; // 
	final static byte ESP_Prefix_SendBulk             = (byte)')'       ; // 
	final static byte ESP_Prefix_FileRequest          = (byte)'$'       ; //
	final static byte ESP_Prefix_FileOrder            = (byte)'@'       ; //
	final static byte ESP_Prefix_RequestLCD           = (byte)'~'       ; //     
	final static byte ESP_Prefix_OrderLCD             = (byte)'!'       ; //
	final static byte ESP_Prefix_DiagCmd              = (byte)'#'       ; // 
	final static byte ESP_Prefix_ProgrammingESP       = (byte)'%'       ; // 
	
	
	// ESP Get/Set Number Suffix                        
	final static byte ESP_Suffix_Add_Dat0              = (byte)'0'      ; // 
	
	final static byte ESP_Suffix_Add_Dat9              = (byte)'9'      ; // 
	final static byte ESP_Suffix_NetFlags              = (byte)'a'      ; // 
	final static byte ESP_Suffix_NetStatus             = (byte)'b'      ; // 
	final static byte ESP_Suffix_AppRunningCount       = (byte)'c'      ; // 
	final static byte ESP_Suffix_InternetStatus        = (byte)'d'      ; // 
	final static byte ESP_Suffix_DHCP_Status           = (byte)'e'      ; // 
	final static byte ESP_Suffix_PublicIP              = (byte)'f'      ; // 
	final static byte ESP_Suffix_AP_IP_Addr            = (byte)'g'      ; // 
	final static byte ESP_Suffix_AP_SubnetMask         = (byte)'h'      ; // 
	final static byte ESP_Suffix_AP_DevicesConnected   = (byte)'i'      ; // 
	final static byte ESP_Suffix_AP_MaxDevices         = (byte)'j'      ; // 
	final static byte ESP_Suffix_AP_MacOUI             = (byte)'k'      ; // 
	final static byte ESP_Suffix_AP_MacNIC             = (byte)'l'      ; // 
	final static byte ESP_Suffix_Station_IP_Addr       = (byte)'m'      ; // 
	final static byte ESP_Suffix_Station_SubnetMask    = (byte)'n'      ; // 
	final static byte ESP_Suffix_Station_GateWay       = (byte)'o'      ; // 
	final static byte ESP_Suffix_Station_DNS_Addr      = (byte)'p'      ; // 
	final static byte ESP_Suffix_Station_MacOUI        = (byte)'q'      ; // 
	final static byte ESP_Suffix_Station_MacNIC        = (byte)'r'      ; // 
	final static byte ESP_Suffix_Station_RSSI          = (byte)'s'      ; // 
	final static byte ESP_Suffix_QuantitySSID          = (byte)'t'      ; // 
	final static byte ESP_Suffix_Ping                  = (byte)'u'      ; // 
	final static byte ESP_Suffix_PortHTTP              = (byte)'v'      ; // 
	final static byte ESP_Suffix_BaudRate              = (byte)'w'      ; //
	
	
	final static byte ESP_Suffix_AccessLevel           = (byte)'A'      ; // 
	final static byte ESP_Suffix_SerialNumber          = (byte)'B'      ; // 
	final static byte ESP_Suffix_Revision              = (byte)'C'      ; // 
	final static byte ESP_Suffix_HideWeigh             = (byte)'D'      ; // 
	final static byte ESP_Suffix_IDIndex               = (byte)'E'      ; // 
	final static byte ESP_Suffix_ReportMode            = (byte)'F'      ; // 
	
	
	final static byte ESP_Suffix_KeyBoard              = (byte)'J'      ; //
	
	
	
	// ESP Get/Set String Suffix                        
	final static byte ESP_Suffix_DatStr0               = (byte)'0'      ; // 
	 
	final static byte ESP_Suffix_DatStr9               = (byte)'9'      ; // 
	final static byte ESP_Suffix_StationSSID           = (byte)'a'      ; // 
	final static byte ESP_Suffix_StationPass           = (byte)'b'      ; // 
	final static byte ESP_Suffix_HostName              = (byte)'c'      ; // 
	final static byte ESP_Suffix_AP_Pass               = (byte)'d'      ; // 
	final static byte ESP_Suffix_AP_SSID               = (byte)'e'      ; // 
	final static byte ESP_Suffix_MessageStr            = (byte)'f'      ; // 
	final static byte ESP_Suffix_AccessPass            = (byte)'g'      ; // 
	final static byte ESP_Suffix_UserName              = (byte)'h'      ; // 
	final static byte ESP_Suffix_TransmitFileName      = (byte)'i'      ; //
	final static byte ESP_Suffix_FirmwareHash          = (byte)'k'      ; //
	
	
	// ESP Request/Order Suffix                         
	final static byte ESP_Suffix_Status                = (byte)'0'      ; // 
	final static byte ESP_Suffix_Weigh                 = (byte)'1'      ; // 
	final static byte ESP_Suffix_Power                 = (byte)'2'      ; // 
	final static byte ESP_Suffix_Tare                  = (byte)'3'      ; // 
	
	final static byte ESP_Suffix_SortRSSI              = (byte)'5'      ; // 
	final static byte ESP_Suffix_Receipt               = (byte)'6'      ; // 
	final static byte ESP_Suffix_WhatDateTime          = (byte)'7'      ; // 
	final static byte ESP_Suffix_Bell                  = (byte)'8'      ; // 
	final static byte ESP_Suffix_DateTimeInfo          = (byte)'9'      ; // 
	final static byte ESP_Suffix_MessageBox            = (byte)'a'      ; // 
	final static byte ESP_Suffix_BasicData             = (byte)'b'      ; // 
	final static byte ESP_Suffix_Response              = (byte)'c'      ; // 
	final static byte ESP_Suffix_ConfirmSettings       = (byte)'d'      ; // 
	final static byte ESP_Suffix_Report                = (byte)'e'      ; // 
	final static byte ESP_Suffix_SystemLanguage        = (byte)'f'      ; // 
	final static byte ESP_Suffix_GoToChart             = (byte)'g'      ; // 
	final static byte ESP_Suffix_MultiSettings         = (byte)'h'      ; //
	
	
	// ESP Receive/Send Bulk Suffix                    
	final static byte ESP_Suffix_Bulk_Receipt          = (byte)'R'      ; // 
	final static byte ESP_Suffix_Bulk_Report           = (byte)'P'      ; // 
	                
	
	// ESP Receive/Send File Suffix
	final static byte ESP_Suffix_ReceiveFile          = (byte)'r'       ; //
	final static byte ESP_Suffix_SendFile             = (byte)'s'       ; //
	
	
	// ESP RequestLCD/OrderLCD  Suffix
	final static byte ESP_Suffix_MirrorLCD            = (byte)'a'       ; //
	final static byte ESP_Suffix_MonitorLCD           = (byte)'b'       ; //
	final static byte ESP_Suffix_setBlockLCD          = (byte)'c'       ; //
	final static byte ESP_Suffix_FillLCD              = (byte)'d'       ; //
	final static byte ESP_Suffix_ClearLCD             = (byte)'e'       ; //
	
	
	
	// Diag/Programmer Board Commands Suffix            
	final static byte Diag_Suffix_SetLED              = (byte)'l'       ; // 
	final static byte Diag_Suffix_DataFlagBits        = (byte)'d'       ; // 
	final static byte Diag_Suffix_Programming_ESP     = (byte)'E'       ; // 
	final static byte Diag_Suffix_Programming_AVR     = (byte)'V'       ; // 
	final static byte Diag_Suffix_ExitProgramming     = (byte)'X'       ; // 
	
	
	final static byte ESP_Prefix_ProgramRequest       = (byte)'P'       ; //
	
	//  Common Standard RFC Response Codes
	//
	//  +------+-------------------------------+
	//  | Code | Reason-Phrase                 |
	//  +------+-------------------------------+
	//  | 100  | Continue                      |
	//  | 101  | Switching Protocols           |
	//  | 200  | OK                            |
	//  | 201  | Created                       |
	//  | 202  | Accepted                      |
	//  | 203  | Non-Authoritative Information |
	//  | 204  | No Content                    |
	//  | 205  | Reset Content                 |
	//  | 206  | Partial Content               |
	//  | 300  | Multiple Choices              |
	//  | 301  | Moved Permanently             |
	//  | 302  | Found                         |
	//  | 303  | See Other                     |
	//  | 304  | Not Modified                  |
	//  | 305  | Use Proxy                     |
	//  | 307  | Temporary Redirect            |
	//  | 400  | Bad Request                   |
	//  | 401  | Unauthorized                  |
	//  | 402  | Payment Required              |
	//  | 403  | Forbidden                     |
	//  | 404  | Not Found                     |
	//  | 405  | Method Not Allowed            |
	//  | 406  | Not Acceptable                |
	//  | 407  | Proxy Authentication Required |
	//  | 408  | Request Timeout               |
	//  | 409  | Conflict                      |
	//  | 410  | Gone                          |
	//  | 411  | Length Required               |
	//  | 412  | Precondition Failed           |
	//  | 413  | Payload Too Large             |
	//  | 414  | URI Too Long                  |
	//  | 415  | Unsupported Media Type        |
	//  | 416  | Range Not Satisfiable         |
	//  | 417  | Expectation Failed            |
	//  | 426  | Upgrade Required              |
	//  | 500  | Internal Server Error         |
	//  | 501  | Not Implemented               |
	//  | 502  | Bad Gateway                   |
	//  | 503  | Service Unavailable           |
	//  | 504  | Gateway Timeout               |
	//  | 505  | HTTP Version Not Supported    |
	//  +------+-------------------------------+
	
	final static byte result_Undefined              = (byte)0xff     ; // Used when clearing the response code
	
	// ESP Message Response Codes
	final static byte result_Success                = (byte)0x0      ; // The request was understood, finished executing without any errors
	final static byte result_Fail                   = (byte)0x1      ; // The request was understood, attempted to execute, but failed to finish
	final static byte result_Reject                 = (byte)0x2      ; // The request is valid, however refusing to be executed
	final static byte result_Processing             = (byte)0x3      ; // The request is currently executing, requires time to finish
	final static byte result_Not_Found              = (byte)0x4      ; // The request was understood, however no matching results exist
	final static byte result_Unauthorised           = (byte)0x5      ; // The user does not have permission to execute the request
	final static byte result_NotAcceptable          = (byte)0x6      ; // The request cannot be executed in the current conditions
	final static byte result_Cancelled              = (byte)0x7      ; // The request Cancelled by user or abort by system
	final static byte result_Creation_Error         = (byte)0x8      ; // The request Cancelled by Creation_Error
	
	// ------------------------------------------------------------
	
	final static byte ReadyFor_GetData             = (byte)0xC5      ; //
	final static byte program_PocketSize           = (byte)0x40      ; // 64 == 0x40 (must be define by hex)
	
	
	
	
	
	final static byte BR_1200     = (byte)0x40      ; //
	final static byte BR_2400     = (byte)0xA0      ; //
	final static byte BR_4800     = (byte)0xCF      ; //
	final static byte BR_9600     = (byte)0x67      ; //
	final static byte BR_14400    = (byte)0x44      ; //
	final static byte BR_19200    = (byte)0x33      ; //
	final static byte BR_38400    = (byte)0x19      ; //
	final static byte BR_56000    = (byte)0x11      ; //
	final static byte BR_57600    = (byte)0x10      ; //         
	final static byte BR_115200   = (byte)0x08      ; //
	
	final static byte  UndefIndex_ =             0;
	
	final static byte        UnknownLevel_ =           0;
	final static byte        OperatorLevel_ =          20;
	final static byte        AdministerLevel_ =        21;
	final static byte        RemoteUserLevel_ =        22;
	final static byte        PandPinLevel_ =           23;
	final static byte        PandLevel_ =              24;
	final static byte        PandCodeLevel_ =          25;
	final static byte        RemoteManagerLevel_ =     26;
	final static byte        DesignerLevel_ =          27;
	final static byte        NotAccessLevel_ =         28;
	
	final static byte        BootingIndex_ =            0;
	final static byte        MenuIndex_ =               10;
	final static byte        FormIndex_ =               11;
	final static byte        ListIndex_ =               12;
	final static byte        PageIndex_ =               13;
	final static byte        ReserveIndex_ =            14;
	
	final static byte MainMenuIndex_ =                  (byte)1;
	final static byte ScaleMenuIndex_ =                 (byte)2;
	final static byte MemoryMenuIndex_ =                (byte)3;
	final static byte ReportMenuIndex_ =                (byte)4;
	final static byte SettingMenuIndex_ =               (byte)5;
	final static byte PasswordMenuIndex_ =              (byte)6;
	final static byte CalibrateMenuIndex_ =              (byte)7;
	final static byte DLC_CalibrateMenuIndex_ =          (byte)8;
	final static byte WiFiSettingsMenuIndex_ =          (byte)9;
	
	final static byte TimeDateFormIndex_ =              (byte)30;
	final static byte CapacityFormIndex_ =              (byte)31;
	final static byte RelayFormIndex_ =                 (byte)32;
	final static byte LotFormIndex_ =                   (byte)33;
	final static byte CarFormIndex_ =                   (byte)34;
	final static byte CalibWeighFormIndex_ =            (byte)35;
	final static byte CalibLoadcellFormIndex_ =         (byte)36;
	final static byte MultiRangeFormIndex_ =            (byte)37;
	final static byte FilterSetFormIndex_ =             (byte)38;
	final static byte ZeroPointFormIndex_ =             (byte)39;
	final static byte StabilityFormIndex_ =             (byte)40;
	final static byte PassPandFormIndex_ =              (byte)41;
	final static byte PassAdminFormIndex_ =             (byte)42;
	final static byte PassOperatorFormIndex_ =          (byte)43;
	final static byte LCDFormIndex_ =                   (byte)44;
	final static byte DefineOperatorFormIndex_ =        (byte)45;
	final static byte SpecialFormIndex_ =               (byte)46;
	final static byte PackWeighFormIndex_ =             (byte)47;
	final static byte ScaleFeeFormIndex_ =              (byte)48;
	final static byte SetFactoryFormIndex_ =            (byte)49;
	final static byte LoadScaleFormIndex_ =             (byte)50;
	final static byte ReceiptPrintFormIndex_ =          (byte)51;
	final static byte ChequeAndPinFormIndex_ =          (byte)52;
	final static byte PinCodeFormIndex_ =               (byte)53;
	final static byte ChequeFormIndex_ =                (byte)54;
	final static byte DailyReportIndex_ =               (byte)55;
	final static byte LotReportIndex_ =                 (byte)56;
	final static byte PlateReportIndex_ =               (byte)57;
	final static byte ReceiptScaleIndex_ =              (byte)58;
	final static byte ReceiptHeaderIndex_ =             (byte)59;
	final static byte ReceiptFooterIndex_ =             (byte)60;
	final static byte ReceiptNumberIndex_ =             (byte)61;
	final static byte ReceiptFormatIndex_ =             (byte)62;
	final static byte ReceiptSpaceIndex_ =              (byte)63;
	final static byte PrinterTypeFormIndex_ =          (byte)64;
	final static byte SerialPortFormIndex_ =            (byte)65;
	final static byte BalanceFormIndex_ =               (byte)66;
	final static byte ADCBackUpFormIndex_ =             (byte)67;
	final static byte DeleteReportFormIndex_ =          (byte)68;
	final static byte FormatMemoryFormIndex_ =          (byte)69;
	final static byte LoadCellCorrectionIndex_ =         (byte)70;
	final static byte DLC_IdConfigIndex_ =              (byte)71;
	final static byte DLC_ManualCalibrateIndex_ =        (byte)72;
	final static byte DLC_BrandIndex_ =                 (byte)73;
	final static byte WiFiRemotePassFormIndex_ =        (byte)74;
	final static byte WiFiRemoteManagerPassFormIndex_ = (byte)75;
	final static byte ASA_WiFiComFormIndex_ =           (byte)76;
	final static byte ASA_USBMMC_FormIndex_ =           (byte)77;
	
	final static byte LotListIndex_ =                   (byte)130;
	final static byte CarListIndex_ =                   (byte)131;
	final static byte Car1ListIndex_ =                  (byte)132;
	final static byte OperatorListIndex_ =              (byte)133;
	final static byte ScaleFeeListIndex_ =              (byte)134;
	final static byte WiFiList_Index_ =                 (byte)135;
	
	final static byte IntroductionIndex_ =              (byte)160;
	final static byte LanguageIndex_ =                  (byte)161;
	final static byte PowerSupplyIndex_ =               (byte)162;
	final static byte OperatorIndex_ =                  (byte)163;
	final static byte ReadingIndex_ =                   (byte)164;
	final static byte DesktopIndex_ =                   (byte)165;
	final static byte UserChangeIndex_ =                (byte)166;
	final static byte SelfTestIndex_ =                  (byte)167;
	final static byte UnKnownLoadcellIndex_ =           (byte)168;
	final static byte DLC_CalibWeighIndex_ =            (byte)169;
	final static byte DLC_DisplayFactorIndex_ =         (byte)170;
	final static byte ASA_DebugDLCPCBIndex_ =           (byte)171;
	final static byte WiFiStationSetIndex_ =            (byte)172;
	final static byte WiFiAP_Set_Index_ =               (byte)173;
	final static byte WiFiStationStatusIndex_ =         (byte)174;
	final static byte WiFiAP_Status_Index_ =            (byte)175;
	final static byte WiFiDiagnosticIndex_ =            (byte)176;
	final static byte WiFiPortServiceIndex_ =           (byte)177;
	final static byte WiFiRemoteUserPageIndex_ =        (byte)178;
	final static byte WiFiRemotePandPageIndex_ =        (byte)179;
	final static byte WiFiRemoteManagerPageIndex_ =     (byte)180;
	final static byte ESP_ProgrammingPageIndex_ =       (byte)181;
	final static byte ASA_TerminalWiFiIndex_ =          (byte)182;
	
	//_________________________  Generated by ESP_Master_Common_Convertor end
}
